<Touchpanel>:
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
            #source: './images/pidubs-normal.png'
            #source: './images/background_options/cherry_blossoms_lamp.png'
            source: self.get_background()
    orientation: 'vertical'
    padding: [0, 0, 0, 0]
    TopBar:
        background_color: 'black'
        id: topbar
        size_hint: 1, 10
        text: 'topbar'
    Desktop:
        padding: [5, 5, 5, 5]
        orientation: 'horizontal'
        size_hint: 1, 90
        PowerInput:
            size_hint: 45, 1
            orientation: 'vertical'
            PowerButton:
                background_color: 'purple'
                id: power
                size_hint: 1, 15
                text: 'power'
            InputButtons:
                cols: 2
                rows: 2
                size_hint: 1, 85
                InputButton:
                    background_color: 'green'
                    id: podium
                    text: 'podium'
                InputButton:
                    background_color: 'blue'
                    id: usbc
                    text: 'usbc'
                InputButton:
                    background_color: 'yellow'
                    id: hdmi
                    text: 'hdmi'
                InputButton:
                    background_color: 'red'
                    id: vga
                    text: 'vga'
        BlankSpace:
            size_hint: 30, 1
        ImageButtons:
            size_hint: 15, 1
            orientation: 'vertical'
            LaterUseBlank:
                size_hint: 1, 15
            BlankButton:
                background_color: 'purple'
                id: blank
                size_hint: 1, 42.5
                text: 'blank'                    
            FreezeButton:
                background_color: 'purple'
                id: freeze
                size_hint: 1, 42.5
                text: 'freeze' 
        SoundControls:
            size_hint: 10, 1
            orientation: 'vertical'
            VolumeLabel:
                background_color: 'white'
                color: 'purple'
                disabled: 'True'
                halign: 'center'
                size_hint: 1, 10
                text: 'Volume\n' + str(int(volume.value))
            VolumeSlider:
                cursor_image: './images/w-logo.png'
                cursor_width: '48sp'
                id: volume
                min: 0
                max: 100
                orientation: 'vertical'
                step: 1
                size_hint: 1, 75
                text: 'volume'
                value: 50
            MuteButton:
                background_color: 'purple'
                id: mute
                size_hint: 1, 15
                text: 'mute'