<Touchpanel>:
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
            source: self.get_background()
    orientation: 'vertical'
    padding: [5, 5, 5, 5]
    #TopBar:
    #    background_color: 'black'
    #    id: topbar
    #    size_hint: 1, 10
    #    text: 'topbar'
    Desktop:
        padding: [5, 5, 5, 5]
        orientation: 'horizontal'
        size_hint: 1, 90
        PowerInput:
            size_hint: 45, 1
            orientation: 'vertical'
            PowerButtonContainer:
                padding: [10, 0]
                size_hint: 1, 15
                spacing: 5            
                PowerButton:
                    id: power
                    text: 'power'
            InputButtons:
                cols: 2
                padding: [10]
                rows: 2
                size_hint: 1, 85
                spacing: 5
                InputButton:
                    group: 'input_buttons'
                    id: podium
                    text: 'podium'
                InputButton:
                    group: 'input_buttons'
                    id: usbc
                    text: 'usbc'
                InputButton:
                    group: 'input_buttons'               
                    id: hdmi
                    text: 'hdmi'
                InputButton:
                    group: 'input_buttons'               
                    id: vga
                    text: 'vga'
        BlankSpace:
            size_hint: 25, 1
        ImageButtons:
            padding: [10]
            size_hint: 20, 1
            spacing: 5
            orientation: 'vertical'
            LaterUseBlank:
                size_hint: 1, 15
            BlankButton:
                id: blank
                size_hint: 1, 42.5
                text: 'blank'                    
            FreezeButton:
                id: freeze
                size_hint: 1, 42.5
                text: 'freeze' 
        SoundControls:
            size_hint: 10, 1
            orientation: 'vertical'
            VolumeLabel:
                background_color: 'white'
                disabled: 'True'
                halign: 'center'
                size_hint: 1, 10
                text: 'Volume\n' + str(int(volume.value))
            VolumeSlider:
                cursor_image: './images/w-logo.png'
                cursor_width: '48sp'
                id: volume
                min: 0
                max: 100
                orientation: 'vertical'
                step: 1
                size_hint: 1, 75
                text: 'volume'
                value: 50
            MuteButton:
                id: mute
                size_hint: 1, 15
                text: 'mute'