<Touchpanel>:
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
            #source: './images/pidubs-normal.png'
            #source: './images/background_options/cherry_blossoms_lamp.png'
            source: self.get_background()
    BoxLayout:
        orientation: 'vertical'
        Button:
            background_color: 'black'
            id: topbar
            size_hint: 1, 10
            text: 'topbar'
        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, 90
            BoxLayout:
                size_hint: 45, 1
                orientation: 'vertical'
                Button:
                    background_color: 'purple'
                    id: power
                    size_hint: 1, 15
                    text: 'power'
                GridLayout:
                    cols: 2
                    rows: 2
                    size_hint: 1, 85
                    Button:
                        background_color: 'green'
                        id: podium
                        text: 'podium'
                    Button:
                        background_color: 'blue'
                        id: usbc
                        text: 'usbc'
                    Button:
                        background_color: 'yellow'
                        id: hdmi
                        text: 'hdmi'
                    Button:
                        background_color: 'red'
                        id: vga
                        text: 'vga'
            Label:
                size_hint: 30, 1
            BoxLayout:
                size_hint: 15, 1
                orientation: 'vertical'
                Label:
                    size_hint: 1, 15
                Button:
                    background_color: 'purple'
                    id: blank
                    size_hint: 1, 42.5
                    text: 'blank'                    
                Button:
                    background_color: 'purple'
                    id: freeze
                    size_hint: 1, 42.5
                    text: 'freeze' 
            BoxLayout:
                size_hint: 10, 1
                orientation: 'vertical'
                Label:
                    color: 'black'
                    size_hint: 1, 10
                    text: 'Volume'
                Slider:
                    id: volume
                    orientation: 'vertical'
                    size_hint: 1, 75
                    text: 'volume'
                Button:
                    background_color: 'purple'
                    id: mute
                    size_hint: 1, 15
                    text: 'mute'